name: migx
description: A Mig33-inspired chat app.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7             # For selecting/uploading images
  flutter_linkify: ^6.0.0          # To make links clickable in text
  intl: ^0.18.1                    # For formatting date/time

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/logo.png
    - assets/avatar.png
    - assets/emojis/
    - assets/gifts/
    - assets/avatars/